package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDetail<M extends BaseDetail<M>> extends Model<M> implements IBean {

	public void setDetailID(java.lang.String detailID) {
		set("detailID", detailID);
	}

	public java.lang.String getDetailID() {
		return get("detailID");
	}

	public void setItemID(java.lang.String itemID) {
		set("itemID", itemID);
	}

	public java.lang.String getItemID() {
		return get("itemID");
	}

	public void setDescribleText(java.lang.String describleText) {
		set("describleText", describleText);
	}

	public java.lang.String getDescribleText() {
		return get("describleText");
	}

	public void setDescribleImg(java.lang.String describleImg) {
		set("describleImg", describleImg);
	}

	public java.lang.String getDescribleImg() {
		return get("describleImg");
	}

}
