package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommon<M extends BaseCommon<M>> extends Model<M> implements IBean {

	public void setCommonID(java.lang.String commonID) {
		set("commonID", commonID);
	}

	public java.lang.String getCommonID() {
		return get("commonID");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setCommon(java.lang.String common) {
		set("common", common);
	}

	public java.lang.String getCommon() {
		return get("common");
	}

}
