package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserID(java.lang.String userID) {
		set("userID", userID);
	}

	public java.lang.String getUserID() {
		return get("userID");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setProfileImage(java.lang.String profileImage) {
		set("profileImage", profileImage);
	}

	public java.lang.String getProfileImage() {
		return get("profileImage");
	}

	public void setAddressID(java.lang.Integer addressID) {
		set("addressID", addressID);
	}

	public java.lang.Integer getAddressID() {
		return get("addressID");
	}

}
