package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public void setOrderID(java.lang.String orderID) {
		set("orderID", orderID);
	}

	public java.lang.String getOrderID() {
		return get("orderID");
	}

	public void setUserID(java.lang.String userID) {
		set("userID", userID);
	}

	public java.lang.String getUserID() {
		return get("userID");
	}

	public void setItemDetailID(java.lang.String itemDetailID) {
		set("itemDetailID", itemDetailID);
	}

	public java.lang.String getItemDetailID() {
		return get("itemDetailID");
	}

}
