package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAddress<M extends BaseAddress<M>> extends Model<M> implements IBean {

	public void setAddressID(java.lang.String addressID) {
		set("addressID", addressID);
	}

	public java.lang.String getAddressID() {
		return get("addressID");
	}

	public void setUserID(java.lang.String userID) {
		set("userID", userID);
	}

	public java.lang.String getUserID() {
		return get("userID");
	}

	public void setMoblie(java.lang.String moblie) {
		set("moblie", moblie);
	}

	public java.lang.String getMoblie() {
		return get("moblie");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

}
